CREATE TABLE IF NOT EXISTS `USERS` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  group_id INT,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  google_uid VARCHAR(255) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `SHARE_GROUPS` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner_user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_share_groups_owner_user FOREIGN KEY (owner_user_id) REFERENCES `USERS` (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CATEGORIES` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(20) NOT NULL,
  is_io_type TINYINT(1) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_categoris_user FOREIGN KEY (user_id) REFERENCES `USERS` (id),
  CONSTRAINT fk_categoris_group FOREIGN KEY (group_id) REFERENCES `SHARE_GROUPS` (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `RECEIPTS` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  image_url VARCHAR(2048),
  taken_at DATETIME,
  ocr_status VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_receipts_user FOREIGN KEY (user_id) REFERENCES `USERS` (id),
  CONSTRAINT fk_receipts_group FOREIGN KEY (group_id) REFERENCES `SHARE_GROUPS` (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MONEY_FLOWS` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  category_id INT NOT NULL,
  receiept_id INT,
  group_id INT NOT NULL,
  amount INT NOT NULL,
  expense_date DATE NOT NULL,
  memo VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_money_flow_user FOREIGN KEY (user_id) REFERENCES `USERS` (id),
  CONSTRAINT fk_money_flow_category FOREIGN KEY (category_id) REFERENCES `CATEGORIS` (id),
  CONSTRAINT fk_money_flow_receiept FOREIGN KEY (receiept_id) REFERENCES `RECEIPTS` (id),
  CONSTRAINT fk_money_flow_group FOREIGN KEY (group_id) REFERENCES `SHARE_GROUPS` (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE TABLE IF NOT EXISTS `RECEIPT_ITEMS` (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   receipt_id INT NOT NULL,
--   category_id INT NOT NULL,
--   item_name VARCHAR(255) NOT NULL,
--   price INT NOT NULL,
--   detection_date DATE,
--   CONSTRAINT fk_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES `RECEIPTS` (id),
--   CONSTRAINT fk_receipt_items_category FOREIGN KEY (category_id) REFERENCES `CATEGORIS` (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
