# Generated by Django 6.0.2 on 2026-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_uid",
            field=models.CharField(max_length=255, unique=True, null=True, blank=True),
        ),
    ]
