# Generated by Django 6.0.1 on 2026-02-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(regex=r"^#[0-9A-Fa-f]{6}$")
                ],
            ),
        ),
    ]
