# Generated by Django 6.0.2 on 2026-02-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moneyflow',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sharegroup',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_uid',
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.sharegroup'),
        ),
    ]
