# Generated by Django 6.0.2 on 2026-02-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyflow',
            name='receipt_id',
        ),
    ]
