# Generated by Django 6.0.2 on 2026-02-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_out', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'viewer')},
            },
        ),
    ]
