# Generated by Django 6.0.2 on 2026-02-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_options_alter_moneyflow_options_and_more'),
        ('web', '0002_alter_user_managers_remove_user_name_and_more'),
    ]

    operations = [
    ]
