# Generated by Django 6.0.2 on 2026-02-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_user_image_user_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='image_url',
            new_name='icon',
        ),
    ]
