# Generated by Django 6.0.2 on 2026-02-16 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ledgershare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='member', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SHARE_GROUP_MEMBERS',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ledgershare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ledgershare',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ledgershare',
            name='viewer',
        ),
        migrations.RemoveConstraint(
            model_name='sharegroup',
            name='uq_sharegroup_owner_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='sharegroup',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_share_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sharegroup',
            constraint=models.UniqueConstraint(fields=('created_by_user', 'name'), name='uq_sharegroup_createdby_name'),
        ),
        migrations.AddField(
            model_name='sharegroupmember',
            name='share_group',
            field=models.ForeignKey(db_column='share_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='web.sharegroup'),
        ),
        migrations.AddField(
            model_name='sharegroupmember',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='share_group_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LedgerShare',
        ),
        migrations.RemoveField(
            model_name='sharegroup',
            name='owner_user',
        ),
        migrations.AddConstraint(
            model_name='sharegroupmember',
            constraint=models.UniqueConstraint(fields=('share_group', 'user'), name='uq_share_group_members_group_user'),
        ),
    ]
