# Generated by Django 6.0.2 on 2026-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_user_username'),
        ('web', '0004_sharegroupmember_alter_ledgershare_unique_together_and_more'),
    ]

    operations = [
    ]
