# Generated by Django 6.0.2 on 2026-02-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_merge_20260219_1653'),
        ('web', '0006_user_group'),
    ]

    operations = [
    ]
